language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

branches:
  only:
    - master

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.1
      env: WP_VERSION=latest

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test
      WP_MULTISITE=1 composer test
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer lint
    fi
